services:
  db:
    image: postgres:16-alpine
    container_name: facialy_db
    environment:
      POSTGRES_USER: deveps
      POSTGRES_PASSWORD: c0m@nd0G3573!
      POSTGRES_DB: facialy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: