services:
  db:
    image: postgres:16-alpine
    container_name: facialy_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: facialy_web
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
