# Generated by Django 6.0.2 on 2026-10-03 05:47

import django.db.models.deletion
from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    # El serializer anterior guardaba '' y dos '' chocan con la restricción unique
    apps.get_model('core', 'Employee').objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_optional_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='reason',
            field=models.CharField(blank=True, choices=[('', 'Ninguno'), ('INACTIVE', 'Empleado inactivo'), ('OUTSIDE_SCHEDULE', 'Fuera de horario')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.employee')),
            ],
        ),
        migrations.RunPython(blank_emails_to_null, migrations.RunPython.noop),
    ]
